// Code generated by dagger-compiler.  Do not edit.
package com.studySnake.snake;


import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binder<BaseActivity>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 * 
 * Owning the dependency links between {@code BaseActivity} and its
 * dependencies.
 * 
 * Being a {@code Provider<BaseActivity>} and handling creation and
 * preparation of object instances.
 * 
 * Being a {@code MembersInjector<BaseActivity>} and handling injection
 * of annotated fields.
 */
public final class BaseActivity$$InjectAdapter extends Binding<BaseActivity>
    implements Provider<BaseActivity>, MembersInjector<BaseActivity> {
  private Binding<com.squareup.otto.Bus> bus;

  public BaseActivity$$InjectAdapter() {
    super("com.studySnake.snake.BaseActivity", "members/com.studySnake.snake.BaseActivity", NOT_SINGLETON, BaseActivity.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    bus = (Binding<com.squareup.otto.Bus>) linker.requestBinding("com.squareup.otto.Bus", BaseActivity.class, getClass().getClassLoader());
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(bus);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<BaseActivity>}.
   */
  @Override
  public BaseActivity get() {
    BaseActivity result = new BaseActivity();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<BaseActivity>}.
   */
  @Override
  public void injectMembers(BaseActivity object) {
    object.bus = bus.get();
  }
}
