// Code generated by dagger-compiler.  Do not edit.
package com.studySnake.snake;


import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binder<CreateAccountFragment>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 * 
 * Owning the dependency links between {@code CreateAccountFragment} and its
 * dependencies.
 * 
 * Being a {@code Provider<CreateAccountFragment>} and handling creation and
 * preparation of object instances.
 * 
 * Being a {@code MembersInjector<CreateAccountFragment>} and handling injection
 * of annotated fields.
 */
public final class CreateAccountFragment$$InjectAdapter extends Binding<CreateAccountFragment>
    implements Provider<CreateAccountFragment>, MembersInjector<CreateAccountFragment> {
  private Binding<com.studySnake.snake.model.UserManager> userM;
  private Binding<BaseFragment> supertype;

  public CreateAccountFragment$$InjectAdapter() {
    super("com.studySnake.snake.CreateAccountFragment", "members/com.studySnake.snake.CreateAccountFragment", NOT_SINGLETON, CreateAccountFragment.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    userM = (Binding<com.studySnake.snake.model.UserManager>) linker.requestBinding("com.studySnake.snake.model.UserManager", CreateAccountFragment.class, getClass().getClassLoader());
    supertype = (Binding<BaseFragment>) linker.requestBinding("members/com.studySnake.snake.BaseFragment", CreateAccountFragment.class, getClass().getClassLoader(), false, true);
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(userM);
    injectMembersBindings.add(supertype);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<CreateAccountFragment>}.
   */
  @Override
  public CreateAccountFragment get() {
    CreateAccountFragment result = new CreateAccountFragment();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<CreateAccountFragment>}.
   */
  @Override
  public void injectMembers(CreateAccountFragment object) {
    object.userM = userM.get();
    supertype.injectMembers(object);
  }
}
