// Code generated by dagger-compiler.  Do not edit.
package com.studySnake.snake;


import dagger.MembersInjector;
import dagger.internal.Binding;
import dagger.internal.Linker;
import java.util.Set;
import javax.inject.Provider;

/**
 * A {@code Binder<LoginFragment>} implementation which satisfies
 * Dagger's infrastructure requirements including:
 * 
 * Owning the dependency links between {@code LoginFragment} and its
 * dependencies.
 * 
 * Being a {@code Provider<LoginFragment>} and handling creation and
 * preparation of object instances.
 * 
 * Being a {@code MembersInjector<LoginFragment>} and handling injection
 * of annotated fields.
 */
public final class LoginFragment$$InjectAdapter extends Binding<LoginFragment>
    implements Provider<LoginFragment>, MembersInjector<LoginFragment> {
  private Binding<com.studySnake.snake.model.UserManager> userM;
  private Binding<BaseFragment> supertype;

  public LoginFragment$$InjectAdapter() {
    super("com.studySnake.snake.LoginFragment", "members/com.studySnake.snake.LoginFragment", NOT_SINGLETON, LoginFragment.class);
  }

  /**
   * Used internally to link bindings/providers together at run time
   * according to their dependency graph.
   */
  @Override
  @SuppressWarnings("unchecked")
  public void attach(Linker linker) {
    userM = (Binding<com.studySnake.snake.model.UserManager>) linker.requestBinding("com.studySnake.snake.model.UserManager", LoginFragment.class, getClass().getClassLoader());
    supertype = (Binding<BaseFragment>) linker.requestBinding("members/com.studySnake.snake.BaseFragment", LoginFragment.class, getClass().getClassLoader(), false, true);
  }

  /**
   * Used internally obtain dependency information, such as for cyclical
   * graph detection.
   */
  @Override
  public void getDependencies(Set<Binding<?>> getBindings, Set<Binding<?>> injectMembersBindings) {
    injectMembersBindings.add(userM);
    injectMembersBindings.add(supertype);
  }

  /**
   * Returns the fully provisioned instance satisfying the contract for
   * {@code Provider<LoginFragment>}.
   */
  @Override
  public LoginFragment get() {
    LoginFragment result = new LoginFragment();
    injectMembers(result);
    return result;
  }

  /**
   * Injects any {@code @Inject} annotated fields in the given instance,
   * satisfying the contract for {@code Provider<LoginFragment>}.
   */
  @Override
  public void injectMembers(LoginFragment object) {
    object.userM = userM.get();
    supertype.injectMembers(object);
  }
}
